# Define image.
FROM debian:buster-slim
RUN apt-get update && apt-get install -y libssl-dev && rm -rf /var/lib/apt/lists/*

# Copy bin.
COPY gonnamakeit-app/target/release/scripts /usr/local/bin/app

# Copy config.
WORKDIR /usr/src/gmi/
ENV CONFIG_PATH=/usr/src/gmi/config.toml
CMD ["app"]